name: docker_curso
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
